name: clima
description: A new Flutter project.


publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  location: ^4.4.0
  geolocator: ^9.0.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  envied: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.3.3


flutter:


  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
    - family:  Square Peg
      fonts:
        - asset: fonts/SquarePeg-Regular.ttf
          weight: 900