name: Flutter Analyze
on:
  pull_request:
    branches: [ develop,master,main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Analyze
        run: flutter pub get && flutter analyze .
