name: Increase version number

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(awk '/^version:/ {print $2}' pubspec.yaml)"

      - name: Increase version number
        id: increase_version
        run: |
          version=$(echo "${{ steps.get_version.outputs.version }}" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          sed -i "s/version:.*\$/version: $version/" pubspec.yaml
          echo "::set-output name=new_version::$version"

      - name: Commit version changes
        run: |
         git config --global user.name PierreJunior
         git config --global user.email pierresangwa@gmail.com
         git add pubspec.yaml
         git commit -m "Bump version to ${{ steps.increase_version.outputs.new_version }}"
